# Generated by Django 4.1.5 on 2023-01-25 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='album',
        ),
        migrations.AddField(
            model_name='album',
            name='musician',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='musician', to='discs.musician'),
            preserve_default=False,
        ),
    ]
