# Generated by Django 4.1.5 on 2023-01-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discs', '0002_remove_musician_album_album_musician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='last_name',
        ),
        migrations.AddField(
            model_name='musician',
            name='logo',
            field=models.ImageField(default=None, upload_to='logos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musician',
            name='name',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
