# Generated by Django 4.1.5 on 2023-01-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discs', '0003_remove_musician_first_name_remove_musician_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='logo',
        ),
        migrations.AddField(
            model_name='musician',
            name='photo',
            field=models.ImageField(default='photo', upload_to='photos'),
            preserve_default=False,
        ),
    ]
