# Generated by Django 4.1.5 on 2023-01-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discs', '0006_album_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disc',
            name='photo',
            field=models.ImageField(default='disc/', upload_to='disc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disc',
            name='release_date',
            field=models.DateField(default='2023-01-30'),
            preserve_default=False,
        ),
    ]
