# Generated by Django 4.1.5 on 2023-02-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discs', '0008_alter_disc_country_alter_disc_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=models.ImageField(default='default_album.jpg', upload_to='album'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='photo',
            field=models.ImageField(default='default_vinyl.png', upload_to='disc'),
        ),
    ]
